name: Frutia
description: A new Flutter project.
publish_to: "none"

version: 1.0.01+2

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  confetti: ^0.7.0   
  firebase_core: ^3.13.0
  provider: ^6.1.2
  firebase_analytics: ^11.4.5
  flutter_dotenv: ^5.0.2
  card_swiper: ^3.0.1
  google_sign_in: ^6.2.2
  particles_flutter: ^1.0.1
  lottie: ^3.3.0
  shared_preferences: ^2.0.8
  http: ^1.1.0
  permission_handler: ^12.0.0+1
  pinput: ^4.0.0
  carousel_slider: ^5.0.0
  flutter_animate: ^4.5.2
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  flutter_intl_phone_field: ^0.0.7
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.3
  fluttertoast: ^8.2.2
  fl_chart: ^0.65.0
  path_provider: ^2.0.15
  chat_bubbles: ^1.6.0
  timeago: ^3.6.0 
  path: ^1.8.3
  flutter_slidable: ^3.0.1
  dio: ^5.4.1
  clipboard: ^0.1.3
  form_builder_validators: ^10.0.0
  flutter_form_builder: ^9.1.1
  syncfusion_flutter_sliders: ^26.2.14
  video_player: ^2.8.6
  vibration: ^1.8.1
  percent_indicator: ^4.2.3
  flutter_tex: ^4.0.7
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  flutter_chat_bubble: ^2.0.2
  audioplayers: ^5.0.0
  audio_session: ^0.1.18
  pusher_channels_flutter: ^2.2.1
  smooth_page_indicator: ^1.1.0 
  firebase_auth: ^5.5.3
  country_picker: ^2.0.26
  collection: ^1.18.0
  showcaseview: ^4.0.1
  onesignal_flutter: ^5.3.3
  pdf: ^3.10.8
  printing: ^5.11.1
  share_plus: ^7.0.0
  open_file: ^3.5.10
  flutter_custom_tabs: ^2.4.0
  webview_flutter: ^4.13.0
  webview_flutter_wkwebview: ^3.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/fondoFrutia.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/icons/
    - assets/grid/
    - assets/map_style.json
    - assets/logos/
    - assets/fonts/
    - assets/sonidos/
    - .env